services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt.yaml:/app/data/configuration.yaml
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080 # zigbee2mqtt-frontend port
    networks:
      - default
    environment:
      - TZ=Europe/Moscow
    devices:
      # Location of CC2531 USB sniffer
      - /dev/tty0:/dev/ttyACM0
    restart: always

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18
    user: mosquitto
    networks:
      - default
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  redis:
    container_name: redis
    image: redis:alpine3.18
    networks:
      - default
    ports:
      - 6379:6379
    restart: always

  backend:
    container_name: schub-backend
    build:
      context: ./backend
    secrets:
      - source: secret_key
    ports:
      - 5000:5000
    environment:
      - PROD=false
    networks:
      - default
    volumes:
      - ./backend:/app
    stop_grace_period: 1s
    restart: always

  frontend:
    container_name: schub-frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - default
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

networks:
  default:
    driver: bridge
    name: smartcab
