version: "3"

services:
  backend:
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - default
    stop_grace_period: 1s

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - default
    stop_grace_period: 1s

networks:
  default:
    driver: bridge
