version: "3"

services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.33.2
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080 # zigbee2mqtt-frontend port
    environment:
      - TZ=Europe/Moscow
    devices:
      # Location of CC2531 USB sniffer
      - /dev/tty0:/dev/ttyACM0

  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto:2.0.18
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log

  backend:
    container_name: server
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      - default
    stop_grace_period: 1s

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    networks:
      - default
    stop_grace_period: 1s

networks:
  default:
    driver: bridge
