# Zigbee2MQTT configuration file.
#
# This one is located inside a special Docker container runned by Docker Compose.

# allow new devices to join
permit_join: true

# Home Assistant integration (MQTT discovery)
homeassistant: false

frontend: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt

  # MQTT server URL
  server: mqtt://mosquitto

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  # (note: that's all in Docker, not in the host system)
  port: /dev/ttyACM0
